name: GitHub Actions Demo

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  pull_request:
    branches:
      - main
  schedule:
    - cron: '15 6 * * 0'  # Every Sunday at 6:15 UTC
  workflow_dispatch:  # Manually
